import React from 'react';
import { 
  UserGroupIcon, 
  CameraIcon, 
  GiftIcon, 
  AcademicCapIcon,
  CalendarIcon,
  InformationCircleIcon,
  BriefcaseIcon,
  ChartBarIcon,
  ChatBubbleLeftRightIcon,
  ClockIcon,
  Cog6ToothIcon,
  CpuChipIcon,
  DocumentTextIcon,
  EnvelopeIcon,
  EyeIcon,
  FilmIcon,
  GlobeAltIcon,
  HandThumbUpIcon,
  HashtagIcon,
  HeartIcon,
  HomeIcon,
  IdentificationIcon,
  InboxIcon,
  LinkIcon,
  MapPinIcon,
  MegaphoneIcon,
  MicrophoneIcon,
  NewspaperIcon,
  PaintBrushIcon,
  PhoneIcon,
  PhotoIcon,
  PlayIcon,
  PresentationChartLineIcon,
  PuzzlePieceIcon,
  QrCodeIcon,
  QuestionMarkCircleIcon,
  RocketLaunchIcon,
  RssIcon,
  ScissorsIcon,
  ServerIcon,
  ShareIcon,
  ShieldCheckIcon,
  SparklesIcon,
  SpeakerWaveIcon,
  StarIcon,
  TagIcon,
  TicketIcon,
  UserCircleIcon,
  UserIcon,
  UsersIcon,
  VideoCameraIcon,
  WifiIcon,
  WindowIcon,
  WrenchScrewdriverIcon,
  XMarkIcon 
} from '@heroicons/react/24/outline';

// Mappage des icônes par nom
export const iconMap: { [key: string]: React.ComponentType<any> } = {
  // Icônes de base
  user: UserIcon,
  users: UsersIcon,
  userGroup: UserGroupIcon,
  camera: CameraIcon,
  gift: GiftIcon,
  academic: AcademicCapIcon,
  briefcase: BriefcaseIcon,
  chart: ChartBarIcon,
  chat: ChatBubbleLeftRightIcon,
  clock: ClockIcon,
  settings: Cog6ToothIcon,
  cpu: CpuChipIcon,
  document: DocumentTextIcon,
  email: EnvelopeIcon,
  eye: EyeIcon,
  film: FilmIcon,
  globe: GlobeAltIcon,
  like: HandThumbUpIcon,
  hashtag: HashtagIcon,
  heart: HeartIcon,
  home: HomeIcon,
  id: IdentificationIcon,
  inbox: InboxIcon,
  link: LinkIcon,
  location: MapPinIcon,
  megaphone: MegaphoneIcon,
  microphone: MicrophoneIcon,
  news: NewspaperIcon,
  paint: PaintBrushIcon,
  phone: PhoneIcon,
  photo: PhotoIcon,
  play: PlayIcon,
  presentation: PresentationChartLineIcon,
  puzzle: PuzzlePieceIcon,
  qrcode: QrCodeIcon,
  question: QuestionMarkCircleIcon,
  rocket: RocketLaunchIcon,
  rss: RssIcon,
  scissors: ScissorsIcon,
  server: ServerIcon,
  share: ShareIcon,
  shield: ShieldCheckIcon,
  sparkles: SparklesIcon,
  speaker: SpeakerWaveIcon,
  star: StarIcon,
  tag: TagIcon,
  ticket: TicketIcon,
  userCircle: UserCircleIcon,
  video: VideoCameraIcon,
  wifi: WifiIcon,
  window: WindowIcon,
  wrench: WrenchScrewdriverIcon,
  close: XMarkIcon,
  
  // Alias pour la rétrocompatibilité
  default: UserIcon,
  model: UserIcon,
  service: BriefcaseIcon,
  event: CalendarIcon,
  blog: NewspaperIcon,
  contact: EnvelopeIcon,
  about: InformationCircleIcon
};

// Exporter les icônes individuelles pour une utilisation directe si nécessaire
export {
  UserIcon, UsersIcon, UserGroupIcon, CameraIcon, GiftIcon, AcademicCapIcon,
  BriefcaseIcon, ChartBarIcon, ChatBubbleLeftRightIcon, ClockIcon, Cog6ToothIcon,
  CpuChipIcon, DocumentTextIcon, EnvelopeIcon, EyeIcon, FilmIcon, GlobeAltIcon,
  HandThumbUpIcon, HashtagIcon, HeartIcon, HomeIcon, IdentificationIcon,
  InboxIcon, LinkIcon, MapPinIcon, MegaphoneIcon, MicrophoneIcon, NewspaperIcon,
  PaintBrushIcon, PhoneIcon, PhotoIcon, PlayIcon, PresentationChartLineIcon,
  PuzzlePieceIcon, QrCodeIcon, QuestionMarkCircleIcon, RocketLaunchIcon, RssIcon,
  ScissorsIcon, ServerIcon, ShareIcon, ShieldCheckIcon, SparklesIcon, SpeakerWaveIcon,
  StarIcon, TagIcon, TicketIcon, UserCircleIcon, VideoCameraIcon, WifiIcon,
  WindowIcon, WrenchScrewdriverIcon, XMarkIcon
};
