// URLs générées automatiquement depuis ImgBB
export const fashionDayImages = {
  '1.jpg': 'https://i.ibb.co/TVYhQSC/1.jpg',
  '10.jpg': 'https://i.ibb.co/679bPkf/10.jpg',
  '11.jpg': 'https://i.ibb.co/FqcSXn5/11.jpg',
  '12.jpg': 'https://i.ibb.co/W4KBMsk/12.jpg',
  '13.jpg': 'https://i.ibb.co/Z6p1s6f/13.jpg',
  '14.jpg': 'https://i.ibb.co/x0Yykdy/14.jpg',
  '15.jpg': 'https://i.ibb.co/svTvMpN/15.jpg',
  '16.jpg': 'https://i.ibb.co/5xKnhsP/16.jpg',
  '17.jpg': 'https://i.ibb.co/TDPdVRf/17.jpg',
  '18.jpg': 'https://i.ibb.co/hxGRxxS/18.jpg',
  '19.jpg': 'https://i.ibb.co/t6vYppk/19.jpg',
  '2.jpg': 'https://i.ibb.co/cK44qpw/2.jpg',
  '20.jpg': 'https://i.ibb.co/6J42wF7/20.jpg',
  '21.jpg': 'https://i.ibb.co/xtqTLr2/21.jpg',
  '22.jpg': 'https://i.ibb.co/9mX3Xt6/22.jpg',
  '23.jpg': 'https://i.ibb.co/kgCpd0z/23.jpg',
  '24.jpg': 'https://i.ibb.co/C31MRcR/24.jpg',
  '25.jpg': 'https://i.ibb.co/G4X7Wxr/25.jpg',
  '26.jpg': 'https://i.ibb.co/mVnF8fK/26.jpg',
  '27.jpg': 'https://i.ibb.co/dwSCSZB/27.jpg',
  '28.jpg': 'https://i.ibb.co/STNmqkg/28.jpg',
  '29.jpg': 'https://i.ibb.co/93kZkMH/29.jpg',
  '3.jpg': 'https://i.ibb.co/wFZm6PV/3.jpg',
  '30.jpg': 'https://i.ibb.co/kg4rgjb/30.jpg',
  '31.jpg': 'https://i.ibb.co/FfM6Pdg/31.jpg',
  '32.jpg': 'https://i.ibb.co/wNkPZdR/32.jpg',
  '4.jpg': 'https://i.ibb.co/S4rDh0r/4.jpg',
  '5.jpg': 'https://i.ibb.co/JRj8YWh/5.jpg',
  '6.jpg': 'https://i.ibb.co/MTYps3X/6.jpg',
  '7.jpg': 'https://i.ibb.co/svpkspQ/7.jpg',
  '8.jpg': 'https://i.ibb.co/LXjPjXc/8.jpg',
  '9.jpg': 'https://i.ibb.co/rfL9PKy/9.jpg'
};

// Array simple des affiches des mannequins pour Fashion Day Edition 2
// Ordre numérique pour faciliter l'affichage
export const edition2ModelPosters = [
  'https://i.ibb.co/TVYhQSC/1.jpg',
  'https://i.ibb.co/cK44qpw/2.jpg',
  'https://i.ibb.co/wFZm6PV/3.jpg',
  'https://i.ibb.co/S4rDh0r/4.jpg',
  'https://i.ibb.co/JRj8YWh/5.jpg',
  'https://i.ibb.co/MTYps3X/6.jpg',
  'https://i.ibb.co/svpkspQ/7.jpg',
  'https://i.ibb.co/LXjPjXc/8.jpg',
  'https://i.ibb.co/rfL9PKy/9.jpg',
  'https://i.ibb.co/679bPkf/10.jpg',
  'https://i.ibb.co/FqcSXn5/11.jpg',
  'https://i.ibb.co/W4KBMsk/12.jpg',
  'https://i.ibb.co/Z6p1s6f/13.jpg',
  'https://i.ibb.co/x0Yykdy/14.jpg',
  'https://i.ibb.co/svTvMpN/15.jpg',
  'https://i.ibb.co/5xKnhsP/16.jpg',
  'https://i.ibb.co/TDPdVRf/17.jpg',
  'https://i.ibb.co/hxGRxxS/18.jpg',
  'https://i.ibb.co/t6vYppk/19.jpg',
  'https://i.ibb.co/6J42wF7/20.jpg',
  'https://i.ibb.co/xtqTLr2/21.jpg',
  'https://i.ibb.co/9mX3Xt6/22.jpg',
  'https://i.ibb.co/kgCpd0z/23.jpg',
  'https://i.ibb.co/C31MRcR/24.jpg',
  'https://i.ibb.co/G4X7Wxr/25.jpg',
  'https://i.ibb.co/mVnF8fK/26.jpg',
  'https://i.ibb.co/dwSCSZB/27.jpg',
  'https://i.ibb.co/STNmqkg/28.jpg',
  'https://i.ibb.co/93kZkMH/29.jpg',
  'https://i.ibb.co/kg4rgjb/30.jpg',
  'https://i.ibb.co/FfM6Pdg/31.jpg',
  'https://i.ibb.co/wNkPZdR/32.jpg'
];

