// Auto-généré le 08/10/2025 13:17:55
// NE PAS MODIFIER MANUELLEMENT - Utilisez scripts/syncFinancialData.mjs

export interface FinancialData {
  monthlyPayments: Record<string, any>;
  accountingTransactions: any[];
  accountingCategories: any[];
  invoices: any[];
}

export const financialData: FinancialData = {
  "monthlyPayments": [
    {
      "amount": 3000,
      "id": "payment-1758026168792",
      "method": "Virement",
      "modelId": "abongobiang-samantha-casting-1757117669023",
      "modelName": "Samantha Abong obiang",
      "month": "2025-09",
      "notes": "",
      "paymentDate": "2025-09-16",
      "status": "Payé"
    },
    {
      "amount": 1500,
      "id": "payment-1758027075792",
      "method": "Espèces",
      "modelId": "demoted-momoh-chancelle-reg-1757169300067",
      "modelName": "Chancelle MOMOH",
      "month": "2025-09",
      "notes": "",
      "paymentDate": "2025-09-16",
      "status": "Payé"
    },
    {
      "amount": 1500,
      "id": "payment-1758027097061",
      "method": "Virement",
      "modelId": "demoted-nsa-carine-reg-1757166607694",
      "modelName": "Carine NSA",
      "month": "2025-09",
      "notes": "",
      "paymentDate": "2025-09-16",
      "status": "Payé"
    },
    {
      "amount": 15000,
      "id": "payment-1758027449789",
      "method": "Espèces",
      "modelId": "demoted-mabila-nahoumie-reg-1757165673362",
      "modelName": "Nahoumie MABILA",
      "month": "2025-09",
      "notes": "",
      "paymentDate": "2025-09-16",
      "status": "Payé"
    },
    {
      "amount": 15000,
      "id": "payment-1758027493749",
      "method": "Espèces",
      "modelId": "demoted-mbina-esther-reg-1757166512963",
      "modelName": "Esther  MBINA",
      "month": "2025-09",
      "notes": "",
      "paymentDate": "2025-09-16",
      "status": "Payé"
    },
    {
      "amount": 1500,
      "id": "payment-1758027869901",
      "method": "Espèces",
      "modelId": "demoted-mbina-esther-reg-1757166512963",
      "modelName": "Esther  MBINA",
      "month": "2025-09",
      "notes": "",
      "paymentDate": "2025-09-16",
      "status": "Payé"
    },
    {
      "amount": 30000,
      "id": "payment-1758028285357",
      "method": "Espèces",
      "modelId": "expense:Loyer",
      "modelName": "DEPENSE: Loyer",
      "month": "2025-09",
      "notes": "",
      "paymentDate": "2025-09-16",
      "status": "Payé"
    },
    {
      "amount": 1500,
      "id": "payment-1757952107061",
      "method": "Espèces",
      "modelId": "ella-ruth-casting-1757110863258",
      "modelName": "Ruth  Ella ",
      "month": "2025-09",
      "notes": "",
      "paymentDate": "2025-09-15",
      "status": "Payé"
    },
    {
      "amount": 1500,
      "id": "payment-1757952127982",
      "method": "Espèces",
      "modelId": "diane-vanessa",
      "modelName": "Diane Vanessa",
      "month": "2025-09",
      "notes": "",
      "paymentDate": "2025-09-15",
      "status": "Payé"
    },
    {
      "amount": 1500,
      "id": "payment-1757952166505",
      "method": "Virement",
      "modelId": "raida-katsini-1757111463425",
      "modelName": "Raida Katsini",
      "month": "2025-09",
      "notes": "",
      "paymentDate": "2025-09-15",
      "status": "Payé"
    },
    {
      "amount": 1500,
      "id": "payment-1758027466726",
      "method": "Espèces",
      "modelId": "demoted-mounguengui-lorielna-reg-1757169191129",
      "modelName": "Lorielna MOUNGUENGUI",
      "month": "2025-09",
      "notes": "",
      "paymentDate": "2025-09-15",
      "status": "Payé"
    },
    {
      "amount": 1500,
      "id": "payment-1757848256788",
      "method": "Espèces",
      "modelId": "anani-donatien",
      "modelName": "Anani Donatien",
      "month": "2025-09",
      "notes": "",
      "paymentDate": "2025-09-11",
      "status": "Payé"
    },
    {
      "amount": 10000,
      "id": "payment-1757952078498",
      "method": "Espèces",
      "modelId": "aj-caramela",
      "modelName": "AJ Caramela",
      "month": "2025-09",
      "notes": "",
      "paymentDate": "2025-08-15",
      "status": "Payé"
    }
  ],
  "accountingTransactions": [
    {
      "amount": 50000,
      "category": "revenue",
      "createdAt": "2024-01-15T10:00:00Z",
      "createdBy": "admin",
      "currency": "FCFA",
      "date": "2024-01-15",
      "description": "Cotisation mensuelle - Marie Dubois",
      "id": "trans-1",
      "paymentMethod": "bank_transfer",
      "reference": "COT-2024-001",
      "relatedModelId": "model-1",
      "relatedModelName": "Marie Dubois",
      "subcategory": "Cotisations mensuelles"
    },
    {
      "amount": 150000,
      "category": "expense",
      "createdAt": "2024-01-20T14:30:00Z",
      "createdBy": "admin",
      "currency": "FCFA",
      "date": "2024-01-20",
      "description": "Loyer bureau - Janvier 2024",
      "id": "trans-2",
      "paymentMethod": "bank_transfer",
      "reference": "LOY-2024-01",
      "subcategory": "Loyer bureau"
    },
    {
      "amount": 10000,
      "category": "revenue",
      "createdAt": "2025-09-17T00:47:03.072Z",
      "createdBy": "admin",
      "currency": "FCFA",
      "date": "2025-09-16",
      "description": "Paiement en avance (6 mois) - AJ Caramela",
      "id": "migration-aj-caramela-1758070023072",
      "notes": "Paiement avance pour AJ Caramela (Migration)",
      "paymentMethod": "cash",
      "reference": "AVANCE-AJ Caramela-2025",
      "relatedModelId": "aj-caramela",
      "relatedModelName": "AJ Caramela",
      "subcategory": "Paiements en avance"
    },
    {
      "amount": 1500,
      "category": "revenue",
      "createdAt": "2025-09-17T00:47:03.072Z",
      "createdBy": "admin",
      "currency": "FCFA",
      "date": "2025-09-16",
      "description": "Cotisation mensuelle - Anani Donatien",
      "id": "migration-anani-donatien-1758070023072",
      "notes": "\n",
      "paymentMethod": "mobile_money",
      "reference": "COTISATION-Anani Donatien-2025",
      "relatedModelId": "anani-donatien",
      "relatedModelName": "Anani Donatien",
      "subcategory": "Cotisations mensuelles"
    },
    {
      "amount": 1500,
      "category": "revenue",
      "createdAt": "2025-09-17T00:47:03.072Z",
      "createdBy": "admin",
      "currency": "FCFA",
      "date": "2025-09-16",
      "description": "Cotisation mensuelle - Diane Vanessa",
      "id": "migration-diane-vanessa-1758070023072",
      "notes": "Paiement cotisation pour Diane Vanessa (Migration)",
      "paymentMethod": "cash",
      "reference": "COTISATION-Diane Vanessa-2025",
      "relatedModelId": "diane-vanessa",
      "relatedModelName": "Diane Vanessa",
      "subcategory": "Cotisations mensuelles"
    },
    {
      "amount": 1500,
      "category": "revenue",
      "createdAt": "2025-09-17T00:47:03.072Z",
      "createdBy": "admin",
      "currency": "FCFA",
      "date": "2025-09-17",
      "description": "Cotisation mensuelle - Raida Katsini",
      "id": "migration-raida-katsini-1757111463425-1758070023072",
      "notes": "Paiement cotisation pour Raida Katsini (Migration)",
      "paymentMethod": "cash",
      "reference": "COTISATION-Raida Katsini-2025",
      "relatedModelId": "raida-katsini-1757111463425",
      "relatedModelName": "Raida Katsini",
      "subcategory": "Cotisations mensuelles"
    },
    {
      "amount": 1500,
      "category": "revenue",
      "createdAt": "2025-09-17T00:47:03.072Z",
      "createdBy": "admin",
      "currency": "FCFA",
      "date": "2025-09-17",
      "description": "Cotisation mensuelle - Ruth  Ella ",
      "id": "migration-ella-ruth-casting-1757110863258-1758070023072",
      "notes": "Paiement cotisation pour Ruth  Ella  (Migration)",
      "paymentMethod": "cash",
      "reference": "COTISATION-Ruth  Ella -2025",
      "relatedModelId": "ella-ruth-casting-1757110863258",
      "relatedModelName": "Ruth  Ella ",
      "subcategory": "Cotisations mensuelles"
    },
    {
      "amount": 1500,
      "category": "revenue",
      "createdAt": "2025-09-17T00:47:03.072Z",
      "createdBy": "admin",
      "currency": "FCFA",
      "date": "2025-09-17",
      "description": "Cotisation mensuelle - Samantha Abong obiang",
      "id": "migration-abongobiang-samantha-casting-1757117669023-1758070023072",
      "notes": "Paiement cotisation pour Samantha Abong obiang (Migration)",
      "paymentMethod": "cash",
      "reference": "COTISATION-Samantha Abong obiang-2025",
      "relatedModelId": "abongobiang-samantha-casting-1757117669023",
      "relatedModelName": "Samantha Abong obiang",
      "subcategory": "Cotisations mensuelles"
    },
    {
      "amount": 1500,
      "category": "revenue",
      "createdAt": "2025-09-17T00:47:03.072Z",
      "createdBy": "admin",
      "currency": "FCFA",
      "date": "2025-09-17",
      "description": "Cotisation mensuelle - Lorielna MOUNGUENGUI",
      "id": "migration-demoted-mounguengui-lorielna-reg-1757169191129-1758070023072",
      "notes": "Paiement cotisation pour Lorielna MOUNGUENGUI (Migration)",
      "paymentMethod": "cash",
      "reference": "COTISATION-Lorielna MOUNGUENGUI-2025",
      "relatedModelId": "demoted-mounguengui-lorielna-reg-1757169191129",
      "relatedModelName": "Lorielna MOUNGUENGUI",
      "subcategory": "Cotisations mensuelles"
    },
    {
      "amount": 16500,
      "category": "revenue",
      "createdAt": "2025-09-17T00:47:03.072Z",
      "createdBy": "admin",
      "currency": "FCFA",
      "date": "2025-09-17",
      "description": "Cotisation mensuelle + Frais d'inscription - Esther  MBINA",
      "id": "migration-demoted-mbina-esther-reg-1757166512963-1758070023072",
      "notes": "Paiement cotisation_inscription pour Esther  MBINA (Migration)",
      "paymentMethod": "cash",
      "reference": "COTISATION_INSCRIPTION-Esther  MBINA-2025",
      "relatedModelId": "demoted-mbina-esther-reg-1757166512963",
      "relatedModelName": "Esther  MBINA",
      "subcategory": "Cotisations + Inscriptions"
    },
    {
      "amount": 30000,
      "category": "expense",
      "createdAt": "2025-09-17T00:47:53.570Z",
      "createdBy": "admin",
      "currency": "FCFA",
      "date": "2025-09-17",
      "description": "Loyer Complexe Eli",
      "id": "trans-1758070073570",
      "notes": "",
      "paymentMethod": "cash",
      "reference": "",
      "subcategory": "Location & Infrastructure"
    },
    {
      "amount": 1500,
      "category": "revenue",
      "createdAt": "2025-09-17T13:33:26.442Z",
      "createdBy": "admin",
      "currency": "FCFA",
      "date": "2025-09-17",
      "description": "Cotisation mensuelle - Thyrelle EYUI",
      "id": "payment-1758116006441",
      "notes": "Paiement cotisation pour Thyrelle EYUI",
      "paymentMethod": "mobile_money",
      "reference": "COTISATION-Thyrelle EYUI-2025",
      "relatedModelId": "demoted-eyui-thyrelle-reg-1757165275082",
      "relatedModelName": "Thyrelle EYUI",
      "subcategory": "Cotisations mensuelles"
    },
    {
      "amount": 1500,
      "category": "revenue",
      "createdAt": "2025-09-17T18:01:10.023Z",
      "createdBy": "admin",
      "currency": "FCFA",
      "date": "2025-09-17",
      "description": "Cotisation mensuelle - Carine NSA",
      "id": "payment-1758132070023",
      "notes": "Paiement cotisation pour Carine NSA",
      "paymentMethod": "mobile_money",
      "reference": "COTISATION-Carine NSA-2025",
      "relatedModelId": "demoted-nsa-carine-reg-1757166607694",
      "relatedModelName": "Carine NSA",
      "subcategory": "Cotisations mensuelles"
    },
    {
      "amount": 10000,
      "category": "revenue",
      "createdAt": "2025-09-17T18:26:29.407Z",
      "createdBy": "admin",
      "currency": "FCFA",
      "date": "2025-09-17",
      "description": "Cotisation mensuelle - AJ Caramela",
      "id": "payment-1758133589407",
      "notes": "Paiement cotisation pour AJ Caramela",
      "paymentMethod": "cash",
      "reference": "COTISATION-AJ Caramela-2025",
      "relatedModelId": "aj-caramela",
      "relatedModelName": "AJ Caramela",
      "subcategory": "Cotisations mensuelles"
    },
    {
      "amount": 1500,
      "category": "revenue",
      "createdAt": "2025-09-17T18:27:14.014Z",
      "createdBy": "admin",
      "currency": "FCFA",
      "date": "2025-09-17",
      "description": "Cotisation mensuelle - Chancelle MOMOH",
      "id": "payment-1758133634014",
      "notes": "Paiement cotisation pour Chancelle MOMOH",
      "paymentMethod": "cash",
      "reference": "COTISATION-Chancelle MOMOH-2025",
      "relatedModelId": "demoted-momoh-chancelle-reg-1757169300067",
      "relatedModelName": "Chancelle MOMOH",
      "subcategory": "Cotisations mensuelles"
    },
    {
      "amount": 1500,
      "category": "Cotisation",
      "date": "2025-09-19T11:42:45.000Z",
      "description": "Paiement cotisation",
      "id": "trans-1758282165000",
      "modelId": "abongobiang-samantha-casting-1757117669023",
      "modelName": "Samantha Abong obiang",
      "paymentMethod": "mobile_money",
      "type": "credit"
    },
    {
      "amount": 1500,
      "category": "Cotisation",
      "date": "2025-09-19T11:43:01.172Z",
      "description": "Paiement cotisation",
      "id": "trans-1758282181172",
      "modelId": "demoted-mboumba-sarah-reg-1757174728282",
      "modelName": "Sarah MBOUMBA",
      "paymentMethod": "mobile_money",
      "type": "credit"
    },
    {
      "amount": 1500,
      "category": "revenue",
      "createdAt": "2025-09-19T15:16:56.242Z",
      "createdBy": "admin",
      "currency": "FCFA",
      "date": "2025-09-19",
      "description": "Paiement cotisation",
      "id": "trans-1758295016242",
      "notes": "Paiement cotisation pour Aurore KONE",
      "paymentMethod": "mobile_money",
      "reference": "COTISATION-Aurore KONE-2025",
      "relatedModelId": "demoted-kone-aurore-reg-1757170213003",
      "relatedModelName": "Aurore KONE",
      "subcategory": "Cotisations mensuelles"
    },
    {
      "amount": 1500,
      "category": "revenue",
      "createdAt": "2025-09-19T15:17:17.226Z",
      "createdBy": "admin",
      "currency": "FCFA",
      "date": "2025-09-19",
      "description": "Paiement cotisation",
      "id": "trans-1758295037226",
      "notes": "Paiement cotisation pour Lucresse SENDZE",
      "paymentMethod": "mobile_money",
      "reference": "COTISATION-Lucresse SENDZE-2025",
      "relatedModelId": "demoted-sendze-lucresse-reg-1757165465454",
      "relatedModelName": "Lucresse SENDZE",
      "subcategory": "Cotisations mensuelles"
    },
    {
      "amount": 1500,
      "category": "revenue",
      "createdAt": "2025-09-19T18:18:30.206Z",
      "createdBy": "admin",
      "currency": "FCFA",
      "date": "2025-09-19",
      "description": "Paiement cotisation",
      "id": "trans-1758305910206",
      "notes": "Paiement cotisation pour GNIOBO Arselia",
      "paymentMethod": "mobile_money",
      "reference": "COTISATION-GNIOBO Arselia-2025",
      "relatedModelId": "demoted-arselia-gniobo-reg-1757165061845",
      "relatedModelName": "GNIOBO Arselia",
      "subcategory": "Cotisations mensuelles"
    },
    {
      "amount": 1500,
      "category": "revenue",
      "createdAt": "2025-09-19T18:28:54.294Z",
      "createdBy": "admin",
      "currency": "FCFA",
      "date": "2025-09-19",
      "description": "Paiement cotisation",
      "id": "trans-1758306534294",
      "notes": "Paiement cotisation pour Ursula BOUMSO",
      "paymentMethod": "mobile_money",
      "reference": "COTISATION-Ursula BOUMSO-2025",
      "relatedModelId": "boumso-ursula-reg-1757165165045",
      "relatedModelName": "Ursula BOUMSO",
      "subcategory": "Cotisations mensuelles"
    },
    {
      "amount": 1500,
      "category": "revenue",
      "createdAt": "2025-09-19T18:35:43.161Z",
      "createdBy": "admin",
      "currency": "FCFA",
      "date": "2025-09-19",
      "description": "Paiement cotisation",
      "id": "trans-1758306943161",
      "notes": "Paiement cotisation pour Marisca BIVIGOU",
      "paymentMethod": "mobile_money",
      "reference": "COTISATION-Marisca BIVIGOU-2025",
      "relatedModelId": "demoted-bivigou-marisca-reg-1757166828498",
      "relatedModelName": "Marisca BIVIGOU",
      "subcategory": "Cotisations mensuelles"
    },
    {
      "amount": 1500,
      "category": "revenue",
      "createdAt": "2025-09-19T19:19:08.084Z",
      "createdBy": "admin",
      "currency": "FCFA",
      "date": "2025-09-19",
      "description": "Paiement cotisation",
      "id": "trans-1758309548084",
      "notes": "Paiement cotisation pour Alicia MENGUE ",
      "paymentMethod": "mobile_money",
      "reference": "COTISATION-Alicia MENGUE -2025",
      "relatedModelId": "demoted-mengue-alicia-reg-1757166692449",
      "relatedModelName": "Alicia MENGUE ",
      "subcategory": "Cotisations mensuelles"
    },
    {
      "amount": 1500,
      "category": "revenue",
      "createdAt": "2025-09-19T19:37:14.789Z",
      "createdBy": "admin",
      "currency": "FCFA",
      "date": "2025-09-19",
      "description": "Paiement cotisation",
      "id": "trans-1758310634789",
      "notes": "Paiement cotisation pour Chancelia OSSAGHA",
      "paymentMethod": "mobile_money",
      "reference": "COTISATION-Chancelia OSSAGHA-2025",
      "relatedModelId": "demoted-ossagha-chancelia-reg-1757167085109",
      "relatedModelName": "Chancelia OSSAGHA",
      "subcategory": "Cotisations mensuelles"
    },
    {
      "amount": 16500,
      "category": "revenue",
      "createdAt": "2025-09-20T15:55:38.757Z",
      "createdBy": "admin",
      "currency": "FCFA",
      "date": "2025-09-20",
      "description": "Paiement inscription et cotisation",
      "id": "trans-1758383738757",
      "notes": "Paiement cotisation_inscription pour Hawa MOUNDENI",
      "paymentMethod": "mobile_money",
      "reference": "COTISATION_INSCRIPTION-Hawa MOUNDENI-2025",
      "relatedModelId": "demoted-moundeni-hawa-reg-1757168191718",
      "relatedModelName": "Hawa MOUNDENI",
      "subcategory": "Cotisations + Inscriptions"
    },
    {
      "amount": 1500,
      "category": "revenue",
      "createdAt": "2025-09-20T21:01:43.170Z",
      "createdBy": "admin",
      "currency": "FCFA",
      "date": "2025-09-20",
      "description": "Paiement cotisation",
      "id": "trans-1758402103170",
      "notes": "Paiement cotisation pour Styna MOUTSINGA",
      "paymentMethod": "mobile_money",
      "reference": "COTISATION-Styna MOUTSINGA-2025",
      "relatedModelId": "demoted-moutsinga-styna-reg-1757166269970",
      "relatedModelName": "Styna MOUTSINGA",
      "subcategory": "Cotisations mensuelles"
    },
    {
      "amount": 15000,
      "category": "revenue",
      "createdAt": "2025-09-20T21:03:08.467Z",
      "createdBy": "admin",
      "currency": "FCFA",
      "date": "2025-09-20",
      "description": "Paiement inscription",
      "id": "trans-1758402188466",
      "notes": "Paiement inscription pour GNIOBO Arselia",
      "paymentMethod": "mobile_money",
      "reference": "INSCRIPTION-GNIOBO Arselia-2025",
      "relatedModelId": "demoted-arselia-gniobo-reg-1757165061845",
      "relatedModelName": "GNIOBO Arselia",
      "subcategory": "Frais d'inscription"
    },
    {
      "amount": 30000,
      "category": "expense",
      "createdAt": "2025-09-22T21:55:25.442Z",
      "createdBy": "admin",
      "currency": "FCFA",
      "date": "2025-09-22",
      "description": "Emprunt AJ ",
      "id": "trans-expense-2025-09-22-1758578125442",
      "notes": "",
      "paymentMethod": "cash",
      "reference": "",
      "subcategory": "Location & Infrastructure"
    },
    {
      "amount": 1500,
      "category": "Cotisation",
      "date": "2025-09-27T17:36:37.984Z",
      "description": "Paiement cotisation",
      "id": "trans-1758994597984",
      "modelId": "demoted-mickala-anna-reg-1757166173546",
      "modelName": "Anna MICKALA",
      "paymentMethod": "mobile_money",
      "type": "credit"
    },
    {
      "amount": 1500,
      "category": "Cotisation",
      "date": "2025-09-27T17:36:52.813Z",
      "description": "Paiement cotisation",
      "id": "trans-1758994612813",
      "modelId": "demoted-saphou-dorcas-reg-1757167348544",
      "modelName": "Dorcas Moïra SAPHOU",
      "paymentMethod": "mobile_money",
      "type": "credit"
    },
    {
      "amount": 15000,
      "category": "revenue",
      "createdAt": "2025-10-04T11:52:25.298Z",
      "createdBy": "admin",
      "currency": "FCFA",
      "date": "2025-10-04",
      "description": "Paiement inscription",
      "id": "trans-1759578745298",
      "notes": "Paiement inscription pour Aurore KONE",
      "paymentMethod": "mobile_money",
      "reference": "INSCRIPTION-Aurore KONE-2025",
      "relatedModelId": "demoted-kone-aurore-reg-1757170213003",
      "relatedModelName": "Aurore KONE",
      "subcategory": "Frais d'inscription"
    },
    {
      "amount": 15000,
      "category": "revenue",
      "createdAt": "2025-10-04T11:53:15.319Z",
      "createdBy": "admin",
      "currency": "FCFA",
      "date": "2025-10-04",
      "description": "Paiement inscription",
      "id": "trans-1759578795319",
      "notes": "Paiement inscription pour Ursula BOUMSO",
      "paymentMethod": "mobile_money",
      "reference": "INSCRIPTION-Ursula BOUMSO-2025",
      "relatedModelId": "boumso-ursula-reg-1757165165045",
      "relatedModelName": "Ursula BOUMSO",
      "subcategory": "Frais d'inscription"
    },
    {
      "amount": 1500,
      "category": "revenue",
      "createdAt": "2025-10-04T11:53:50.534Z",
      "createdBy": "admin",
      "currency": "FCFA",
      "date": "2025-10-04",
      "description": "Paiement cotisation",
      "id": "trans-1759578830534",
      "notes": "Paiement cotisation pour Hawa MOUNDENI",
      "paymentMethod": "mobile_money",
      "reference": "COTISATION-Hawa MOUNDENI-2025",
      "relatedModelId": "demoted-moundeni-hawa-reg-1757168191718",
      "relatedModelName": "Hawa MOUNDENI",
      "subcategory": "Cotisations mensuelles"
    },
    {
      "amount": 5000,
      "category": "revenue",
      "createdAt": "2025-10-07T14:47:32.421Z",
      "createdBy": "admin",
      "currency": "FCFA",
      "date": "2025-10-07",
      "description": "Avance Inscription Lorielna",
      "id": "trans-revenue-2025-10-07-1759848452421",
      "notes": "",
      "paymentMethod": "mobile_money",
      "reference": "",
      "subcategory": "Cotisations Mannequins"
    }
  ],
  "accountingCategories": [
    {
      "description": "Revenus provenant des cotisations des mannequins",
      "id": "revenue-cotisations",
      "name": "Cotisations Mannequins",
      "subcategories": [
        "Cotisations mensuelles",
        "Cotisations annuelles",
        "Frais d'inscription"
      ],
      "type": "revenue"
    },
    {
      "description": "Revenus provenant des services de l'agence",
      "id": "revenue-services",
      "name": "Services",
      "subcategories": [
        "Booking mannequins",
        "Organisation événements",
        "Formation",
        "Photographie"
      ],
      "type": "revenue"
    },
    {
      "description": "Revenus provenant des partenariats",
      "id": "revenue-partenariats",
      "name": "Partenariats",
      "subcategories": [
        "Sponsors",
        "Collaborations",
        "Publicité"
      ],
      "type": "revenue"
    },
    {
      "description": "Dépenses liées à l'infrastructure",
      "id": "expense-location",
      "name": "Location & Infrastructure",
      "subcategories": [
        "Loyer bureau",
        "Électricité",
        "Internet",
        "Téléphone"
      ],
      "type": "expense"
    },
    {
      "description": "Dépenses de marketing et communication",
      "id": "expense-marketing",
      "name": "Marketing & Communication",
      "subcategories": [
        "Publicité",
        "Réseaux sociaux",
        "Matériel promotionnel",
        "Événements"
      ],
      "type": "expense"
    },
    {
      "description": "Dépenses liées au personnel",
      "id": "expense-personnel",
      "name": "Personnel",
      "subcategories": [
        "Salaires",
        "Formation",
        "Équipement",
        "Déplacements"
      ],
      "type": "expense"
    },
    {
      "description": "Autres dépenses",
      "id": "expense-divers",
      "name": "Divers",
      "subcategories": [
        "Fournitures",
        "Maintenance",
        "Assurance",
        "Autres"
      ],
      "type": "expense"
    }
  ],
  "invoices": []
};

export const financialSummary = {
  lastUpdated: '2025-10-08T12:17:55.143Z',
  monthlyPayments: {
    totalModels: 13,
    modelsUpToDate: 0,
    modelsOverdue: 13,
    totalRevenue: 0
  },
  transactions: {
    total: 34,
    totalRecettes: 0,
    totalDepenses: 0,
    balance: 0
  },
  invoices: {
    total: 0,
    totalAmount: 0,
    paid: 0,
    pending: 0,
    overdue: 0
  }
};
