import { Model } from '../types';

export const models: Model[] = [
  {
    "age": 18,
    "email": "",
    "measurements": {
      "waist": "68cm",
      "hips": "92cm",
      "chest": "79cm",
      "shoeSize": "39"
    },
    "id": "abeme-ophelie-9400",
    "password": "ophelie2026",
    "level": "Pro",
    "username": "Man-PMMO02",
    "name": "Ophélie  ABEME",
    "distinctions": [],
    "quizScores": {},
    "phone": "074926269",
    "location": "",
    "gender": "Femme",
    "experience": "Nouveau mannequin issu du casting. Score: 5.08/10",
    "height": "1.67cm",
    "imageUrl": "https://i.ibb.co/fVBxPNTP/T-shirt.png",
    "isPublic": false,
    "portfolioImages": [],
    "categories": [],
    "journey": "Profil créé automatiquement après validation du casting."
  },
  {
    "isPublic": true,
    "username": "Man-PMMA01",
    "quizScores": {
      "module-1-les-fondamentaux-du-mannequinat": {
        "total": 3,
        "score": 3,
        "timesLeft": 1,
        "timestamp": "2024-07-03T10:00:00Z"
      },
      "module-3-photographie-et-expression-corporelle": {
        "score": 2,
        "total": 2,
        "timesLeft": 0,
        "timestamp": "2024-07-04T10:00:00Z"
      }
    },
    "id": "aj-caramela",
    "gender": "Femme",
    "journey": "AJ a rejoint PMM avec une passion pour la photographie. Son aisance devant l'objectif et sa capacité à se transformer lui ont rapidement ouvert les portes des projets les plus créatifs.",
    "portfolioImages": [
      "https://i.postimg.cc/Xv24Dvp1/NR-09484.jpg",
      "https://i.postimg.cc/59Qbnb1p/NR-09503-Modifier.jpg",
      "https://i.postimg.cc/k5skXhC2/NR-09474.jpg"
    ],
    "measurements": {
      "waist": "60cm",
      "hips": "88cm",
      "shoeSize": "39",
      "chest": "82cm"
    },
    "experience": "Avec son regard perçant et sa polyvalence, AJ excelle dans les shootings éditoriaux et les campagnes publicitaires. Elle a collaboré avec de nombreuses marques locales et photographes de renom.",
    "distinctions": [
      {
        "titles": [
          "Visage de l'Année - Gabon Fashion Awards 2023",
          "Meilleure Collaboration Photo avec NR Picture"
        ],
        "name": "Reconnaissance Artistique"
      }
    ],
    "name": "AJ Caramela",
    "height": "1m75",
    "categories": [
      "Défilé",
      "Commercial",
      "Éditorial"
    ],
    "imageUrl": "https://i.postimg.cc/k5skXhC2/NR-09474.jpg",
    "password": "caramela2024",
    "level": "Pro"
  },
  {
    "phone": "062627199",
    "name": "ABESSOLO Alix",
    "level": "Pro",
    "isPublic": false,
    "quizScores": {},
    "username": "Man-PMMA05",
    "distinctions": [],
    "id": "alix-abessolo-1779",
    "journey": "Profil créé automatiquement après validation du casting.",
    "portfolioImages": [],
    "height": "1.75cm",
    "location": "",
    "email": "",
    "categories": [],
    "measurements": {
      "waist": "70cm",
      "hips": "94cm",
      "shoeSize": "39",
      "chest": "82cm"
    },
    "imageUrl": "https://i.ibb.co/fVBxPNTP/T-shirt.png",
    "experience": "Nouveau mannequin issu du casting. Score: 6.13/10",
    "gender": "Femme",
    "age": 25,
    "password": "abessolo2026"
  },
  {
    "level": "Pro",
    "age": 21,
    "experience": "Nouveau mannequin issu du casting. Score: 6.50/10",
    "journey": "Profil créé automatiquement après validation du casting.",
    "username": "Man-PMMG01",
    "password": "gniobo2026",
    "measurements": {
      "chest": "84cm",
      "shoeSize": "41",
      "waist": "71cm",
      "hips": "89cm"
    },
    "phone": "065983386",
    "gender": "Femme",
    "imageUrl": "https://i.ibb.co/fVBxPNTP/T-shirt.png",
    "name": "GNIOBO Arselia",
    "isPublic": false,
    "height": "1.67cm",
    "location": "",
    "distinctions": [],
    "portfolioImages": [],
    "id": "arselia-gniobo-1845",
    "email": "",
    "quizScores": {},
    "categories": []
  },
  {
    "location": "",
    "imageUrl": "https://i.ibb.co/fVBxPNTP/T-shirt.png",
    "age": 22,
    "name": "Olivia AUBIAN",
    "categories": [],
    "quizScores": {},
    "journey": "Profil créé automatiquement après validation du casting.",
    "portfolioImages": [],
    "distinctions": [],
    "phone": "065281513",
    "password": "olivia2026",
    "experience": "Nouveau mannequin issu du casting. Score: 5.25/10",
    "height": "1.70cm",
    "username": "Man-PMMO01",
    "isPublic": false,
    "id": "aubian-olivia-0814",
    "gender": "Femme",
    "measurements": {
      "waist": "76cm",
      "shoeSize": "39",
      "hips": "89cm",
      "chest": "83cm"
    },
    "level": "Pro",
    "email": ""
  },
  {
    "gender": "Femme",
    "quizScores": {},
    "experience": "Nouveau mannequin issu du casting. Score: 5.50/10",
    "age": 29,
    "location": "",
    "categories": [],
    "level": "Pro",
    "password": "marisca2026",
    "portfolioImages": [],
    "distinctions": [],
    "id": "bivigou-marisca-8498",
    "phone": "074759704",
    "measurements": {
      "shoeSize": "40",
      "waist": "74cm",
      "hips": "100cm",
      "chest": "79cm"
    },
    "imageUrl": "https://i.ibb.co/fVBxPNTP/T-shirt.png",
    "email": "",
    "username": "Man-PMMM02",
    "name": "Marisca BIVIGOU",
    "isPublic": false,
    "journey": "Profil créé automatiquement après validation du casting.",
    "height": "1.74cm"
  },
  {
    "phone": "062635072",
    "name": "Lauretta BOUANGA",
    "location": "",
    "age": 20,
    "quizScores": {},
    "level": "Pro",
    "username": "Man-PMML04",
    "journey": "Profil créé automatiquement après validation du casting.",
    "password": "lauretta2026",
    "portfolioImages": [],
    "measurements": {
      "shoeSize": "40",
      "chest": "95cm",
      "hips": "105cm",
      "waist": "80cm"
    },
    "email": "",
    "categories": [],
    "isPublic": false,
    "height": "1.77cm",
    "experience": "Nouveau mannequin issu du casting. Score: 5.00/10",
    "distinctions": [],
    "id": "bouanga-lauretta-1018",
    "gender": "Femme",
    "imageUrl": "https://i.ibb.co/fVBxPNTP/T-shirt.png"
  },
  {
    "quizScores": {},
    "level": "Pro",
    "categories": [],
    "username": "Man-PMMU01",
    "age": 23,
    "measurements": {
      "shoeSize": "41",
      "chest": "90cm",
      "waist": "86cm",
      "hips": "110cm"
    },
    "height": "1.72cm",
    "phone": "074647206",
    "imageUrl": "https://i.ibb.co/fVBxPNTP/T-shirt.png",
    "name": "Ursula BOUMSO",
    "email": "",
    "location": "",
    "journey": "Profil créé automatiquement après validation du casting.",
    "password": "ursula2026",
    "distinctions": [],
    "id": "boumso-ursula-5045",
    "isPublic": false,
    "gender": "Femme",
    "experience": "Nouveau mannequin issu du casting. Score: 6.63/10",
    "portfolioImages": []
  },
  {
    "quizScores": {},
    "gender": "Femme",
    "username": "Man-PMMM01",
    "experience": "Nouveau mannequin issu du casting. Score: 7.00/10",
    "level": "Pro",
    "isPublic": false,
    "password": "mariam2026",
    "phone": "076486746",
    "portfolioImages": [],
    "journey": "Profil créé automatiquement après validation du casting.",
    "id": "diallo-mariam-9202",
    "distinctions": [],
    "height": "1.90cm",
    "imageUrl": "https://i.ibb.co/fVBxPNTP/T-shirt.png",
    "name": "Mariam DIALLO",
    "age": 20,
    "location": "",
    "measurements": {
      "shoeSize": "41",
      "hips": "106cm",
      "waist": "74cm",
      "chest": "84cm"
    },
    "email": "",
    "categories": []
  },
  {
    "gender": "Femme",
    "level": "Pro",
    "isPublic": false,
    "age": 19,
    "journey": "Profil créé automatiquement après validation du casting.",
    "username": "Man-PMME01",
    "categories": [],
    "location": "",
    "distinctions": [],
    "quizScores": {},
    "imageUrl": "https://i.ibb.co/fVBxPNTP/T-shirt.png",
    "portfolioImages": [],
    "id": "esapi-esther-4485",
    "measurements": {
      "waist": "64cm",
      "chest": "79cm",
      "hips": "92cm",
      "shoeSize": "40"
    },
    "email": "",
    "experience": "Nouveau mannequin issu du casting. Score: 6.75/10",
    "phone": "074483549",
    "password": "esther2026",
    "height": "1.71cm",
    "name": "Esther Esapi"
  },
  {
    "distinctions": [],
    "portfolioImages": [],
    "isPublic": false,
    "id": "eyui-thyrelle-5082",
    "location": "",
    "gender": "Femme",
    "journey": "Profil créé automatiquement après validation du casting.",
    "password": "thyrelle2026",
    "phone": "077916695",
    "categories": [],
    "email": "",
    "age": 22,
    "imageUrl": "https://i.ibb.co/fVBxPNTP/T-shirt.png",
    "quizScores": {},
    "height": "1.64cm",
    "level": "Pro",
    "experience": "Nouveau mannequin issu du casting. Score: 6.00/10",
    "name": "Thyrelle EYUI",
    "measurements": {
      "shoeSize": "38",
      "hips": "96cm",
      "chest": "85cm",
      "waist": "77cm"
    },
    "username": "Man-PMMT01"
  },
  {
    "measurements": {
      "waist": "73cm",
      "shoeSize": "41",
      "hips": "92cm",
      "chest": "84cm"
    },
    "id": "klomegan-sarah-5533",
    "experience": "Nouveau mannequin issu du casting. Score: 6.88/10",
    "gender": "Femme",
    "categories": [],
    "journey": "Profil créé automatiquement après validation du casting.",
    "password": "sarah2026",
    "name": "Sarah KLOMEGAN",
    "level": "Pro",
    "email": "",
    "age": 20,
    "phone": "077102949",
    "username": "Man-PMMS01",
    "quizScores": {},
    "portfolioImages": [],
    "height": "1.80cm",
    "location": "",
    "isPublic": false,
    "imageUrl": "https://i.ibb.co/fVBxPNTP/T-shirt.png",
    "distinctions": []
  },
  {
    "id": "kone-aurore-3003",
    "username": "Man-PMMA02",
    "level": "Pro",
    "isPublic": false,
    "portfolioImages": [],
    "measurements": {
      "chest": "81cm",
      "hips": "95cm",
      "shoeSize": "38",
      "waist": "69cm"
    },
    "experience": "Nouveau mannequin issu du casting. Score: 7.50/10",
    "password": "aurore2026",
    "journey": "Profil créé automatiquement après validation du casting.",
    "email": "",
    "name": "Aurore KONE",
    "gender": "Femme",
    "imageUrl": "https://i.ibb.co/fVBxPNTP/T-shirt.png",
    "distinctions": [],
    "height": "1.69cm",
    "phone": "077340628",
    "age": 20,
    "quizScores": {},
    "location": "",
    "categories": []
  },
  {
    "level": "Pro",
    "password": "ismael2026",
    "isPublic": false,
    "age": 18,
    "categories": [],
    "phone": "074213542",
    "gender": "Homme",
    "imageUrl": "https://i.ibb.co/fVBxPNTP/T-shirt.png",
    "email": "",
    "height": "1.70cm",
    "id": "lloret-ismael-3910",
    "experience": "Nouveau mannequin issu du casting. Score: 5.00/10",
    "quizScores": {},
    "journey": "Profil créé automatiquement après validation du casting.",
    "portfolioImages": [],
    "distinctions": [],
    "measurements": {
      "hips": "93cm",
      "chest": "82cm",
      "shoeSize": "40",
      "waist": "79cm"
    },
    "location": "",
    "username": "Man-PMMI01",
    "name": "Ismael  LLORET"
  },
  {
    "height": "1.63cm",
    "email": "",
    "quizScores": {},
    "portfolioImages": [],
    "gender": "Femme",
    "isPublic": false,
    "measurements": {
      "hips": "89cm",
      "chest": "82cm",
      "waist": "71cm",
      "shoeSize": "39"
    },
    "id": "luciana-aitchedji-5608",
    "experience": "Nouveau mannequin issu du casting. Score: 5.33/10",
    "distinctions": [],
    "categories": [],
    "username": "Man-PMMA07",
    "location": "",
    "imageUrl": "https://i.ibb.co/fVBxPNTP/T-shirt.png",
    "name": "AÏTCHEDJI Luciana",
    "journey": "Profil créé automatiquement après validation du casting.",
    "phone": "066622963",
    "age": 27,
    "level": "Pro",
    "password": "aitchedji2026"
  },
  {
    "categories": [],
    "height": "1.72cm",
    "username": "Man-PMMN02",
    "measurements": {
      "waist": "69cm",
      "shoeSize": "39",
      "chest": "81cm",
      "hips": "93cm"
    },
    "id": "mabila-nahoumie-3362",
    "isPublic": false,
    "portfolioImages": [],
    "age": 21,
    "imageUrl": "https://i.ibb.co/fVBxPNTP/T-shirt.png",
    "phone": "077830646",
    "level": "Pro",
    "password": "nahoumie2026",
    "distinctions": [],
    "name": "Nahoumie MABILA",
    "quizScores": {},
    "gender": "Femme",
    "email": "",
    "experience": "Nouveau mannequin issu du casting. Score: 6.75/10",
    "journey": "Profil créé automatiquement après validation du casting.",
    "location": ""
  },
  {
    "measurements": {
      "hips": "106cm",
      "waist": "86cm",
      "chest": "89cm",
      "shoeSize": "41"
    },
    "isPublic": false,
    "email": "",
    "phone": "065075649",
    "gender": "Femme",
    "quizScores": {},
    "age": 19,
    "location": "",
    "journey": "Profil créé automatiquement après validation du casting.",
    "name": "Esther  MBINA",
    "id": "mbina-esther-2963",
    "imageUrl": "https://i.ibb.co/fVBxPNTP/T-shirt.png",
    "distinctions": [],
    "username": "Man-PMME02",
    "level": "Pro",
    "password": "esther2026",
    "experience": "Nouveau mannequin issu du casting. Score: 6.25/10",
    "categories": [],
    "height": "1.85cm",
    "portfolioImages": []
  },
  {
    "imageUrl": "https://i.ibb.co/fVBxPNTP/T-shirt.png",
    "quizScores": {},
    "isPublic": false,
    "distinctions": [],
    "height": "1.64cm",
    "portfolioImages": [],
    "gender": "Femme",
    "password": "sarah2026",
    "id": "mboumba-sarah-8282",
    "username": "Man-PMMS03",
    "measurements": {
      "hips": "98cm",
      "chest": "83cm",
      "waist": "75cm",
      "shoeSize": "39"
    },
    "location": "",
    "name": "Sarah MBOUMBA",
    "age": 24,
    "level": "Pro",
    "journey": "Profil créé automatiquement après validation du casting.",
    "experience": "Nouveau mannequin issu du casting. Score: 5.83/10",
    "categories": [],
    "email": "",
    "phone": "062133601"
  },
  {
    "distinctions": [],
    "imageUrl": "https://i.ibb.co/fVBxPNTP/T-shirt.png",
    "id": "mengue-alicia-2449",
    "measurements": {
      "chest": "77cm",
      "waist": "69cm",
      "shoeSize": "37",
      "hips": "87cm"
    },
    "experience": "Nouveau mannequin issu du casting. Score: 5.50/10",
    "password": "alicia2026",
    "quizScores": {},
    "categories": [],
    "name": "Alicia MENGUE ",
    "journey": "Profil créé automatiquement après validation du casting.",
    "username": "Man-PMMA06",
    "email": "",
    "portfolioImages": [],
    "isPublic": false,
    "height": "1.60cm",
    "level": "Pro",
    "phone": "065834453",
    "gender": "Femme",
    "location": "",
    "age": 21
  },
  {
    "name": "Anna MICKALA",
    "categories": [],
    "imageUrl": "https://i.ibb.co/fVBxPNTP/T-shirt.png",
    "level": "Pro",
    "isPublic": false,
    "password": "anna2026",
    "phone": "074033548",
    "experience": "Nouveau mannequin issu du casting. Score: 6.25/10",
    "height": "1.74cm",
    "measurements": {
      "shoeSize": "39",
      "hips": "98cm",
      "chest": "82cm",
      "waist": "69cm"
    },
    "journey": "Profil créé automatiquement après validation du casting.",
    "quizScores": {},
    "gender": "Femme",
    "id": "mickala-anna-3546",
    "username": "Man-PMMA04",
    "email": "",
    "distinctions": [],
    "portfolioImages": [],
    "age": 29,
    "location": ""
  },
  {
    "journey": "Profil créé automatiquement après validation du casting.",
    "password": "chancelle2026",
    "gender": "Femme",
    "quizScores": {},
    "isPublic": false,
    "categories": [],
    "name": "Chancelle MOMOH",
    "imageUrl": "https://i.ibb.co/fVBxPNTP/T-shirt.png",
    "level": "Pro",
    "id": "momoh-chancelle-0067",
    "distinctions": [],
    "email": "",
    "phone": "074238963",
    "measurements": {
      "hips": "93cm",
      "waist": "76cm",
      "shoeSize": "41",
      "chest": "86cm"
    },
    "location": "",
    "experience": "Nouveau mannequin issu du casting. Score: 6.75/10",
    "username": "Man-PMMC03",
    "height": "1.76cm",
    "portfolioImages": [],
    "age": 21
  },
  {
    "gender": "Femme",
    "age": 29,
    "portfolioImages": [],
    "password": "raiva2026",
    "experience": "Nouveau mannequin issu du casting. Score: 7.25/10",
    "height": "1.72cm",
    "imageUrl": "https://i.ibb.co/fVBxPNTP/T-shirt.png",
    "isPublic": false,
    "id": "mondjo-raiva-3658",
    "location": "",
    "measurements": {
      "waist": "67cm",
      "chest": "77cm",
      "shoeSize": "38",
      "hips": "97cm"
    },
    "level": "Pro",
    "categories": [],
    "name": "Raïva MONDJO",
    "journey": "Profil créé automatiquement après validation du casting.",
    "email": "",
    "quizScores": {},
    "username": "Man-PMMR02",
    "phone": "074556454",
    "distinctions": []
  },
  {
    "portfolioImages": [],
    "level": "Pro",
    "isPublic": false,
    "categories": [],
    "journey": "Profil créé automatiquement après validation du casting.",
    "username": "Man-PMMH01",
    "gender": "Femme",
    "location": "",
    "height": "1.80cm",
    "name": "Hawa MOUNDENI",
    "phone": "065226181",
    "password": "hawa2026",
    "email": "",
    "id": "moundeni-hawa-1718",
    "imageUrl": "https://i.ibb.co/fVBxPNTP/T-shirt.png",
    "experience": "Nouveau mannequin issu du casting. Score: 4.75/10",
    "measurements": {
      "waist": "64cm",
      "hips": "91cm",
      "shoeSize": "41",
      "chest": "75cm"
    },
    "age": 20,
    "distinctions": [],
    "quizScores": {}
  },
  {
    "location": "",
    "height": "1.78cm",
    "imageUrl": "https://i.ibb.co/fVBxPNTP/T-shirt.png",
    "level": "Pro",
    "phone": "077580358",
    "quizScores": {},
    "journey": "Profil créé automatiquement après validation du casting.",
    "password": "lorielna2026",
    "email": "",
    "experience": "Nouveau mannequin issu du casting. Score: 6.38/10",
    "username": "Man-PMML02",
    "portfolioImages": [],
    "measurements": {
      "shoeSize": "39",
      "waist": "61cm",
      "hips": "94cm",
      "chest": "75cm"
    },
    "age": 23,
    "id": "mounguengui-lorielna-1129",
    "isPublic": false,
    "name": "Lorielna MOUNGUENGUI",
    "gender": "Femme",
    "categories": [],
    "distinctions": []
  },
  {
    "categories": [],
    "id": "moutsinga-styna-9970",
    "phone": "077999683",
    "email": "",
    "height": "1.80cm",
    "isPublic": false,
    "experience": "Nouveau mannequin issu du casting. Score: 5.75/10",
    "location": "",
    "gender": "Femme",
    "measurements": {
      "waist": "75cm",
      "shoeSize": "40",
      "chest": "79cm",
      "hips": "97cm"
    },
    "journey": "Profil créé automatiquement après validation du casting.",
    "name": "Styna MOUTSINGA",
    "quizScores": {},
    "imageUrl": "https://i.ibb.co/fVBxPNTP/T-shirt.png",
    "level": "Pro",
    "age": 23,
    "username": "Man-PMMS04",
    "distinctions": [],
    "portfolioImages": [],
    "password": "styna2026"
  },
  {
    "id": "ndombi-stephie-0023",
    "experience": "Nouveau mannequin issu du casting. Score: 6.75/10",
    "journey": "Profil créé automatiquement après validation du casting.",
    "height": "1.72cm",
    "username": "Man-PMMS02",
    "measurements": {
      "chest": "83cm",
      "shoeSize": "37",
      "hips": "98cm",
      "waist": "74cm"
    },
    "categories": [],
    "level": "Pro",
    "name": "Stephie NDOMBI",
    "email": "",
    "phone": "062360492",
    "gender": "Femme",
    "quizScores": {},
    "age": 29,
    "distinctions": [],
    "imageUrl": "https://i.ibb.co/fVBxPNTP/T-shirt.png",
    "location": "",
    "isPublic": false,
    "portfolioImages": [],
    "password": "stephie2026"
  },
  {
    "categories": [],
    "height": "1.70cm",
    "location": "",
    "imageUrl": "https://i.ibb.co/fVBxPNTP/T-shirt.png",
    "password": "charis2026",
    "isPublic": false,
    "quizScores": {},
    "portfolioImages": [],
    "email": "",
    "measurements": {
      "hips": "97cm",
      "shoeSize": "39",
      "waist": "78cm",
      "chest": "86cm"
    },
    "journey": "Profil créé automatiquement après validation du casting.",
    "username": "Man-PMMC05",
    "distinctions": [],
    "gender": "Femme",
    "age": 21,
    "phone": "077276217",
    "id": "ngo-charis-3008",
    "experience": "Nouveau mannequin issu du casting. Score: 6.25/10",
    "name": "Charis NGO",
    "level": "Pro"
  },
  {
    "age": 24,
    "password": "christy2026",
    "phone": "074661174",
    "name": "Christy NGOUA",
    "username": "Man-PMMC04",
    "imageUrl": "https://i.ibb.co/fVBxPNTP/T-shirt.png",
    "distinctions": [],
    "gender": "Femme",
    "categories": [],
    "quizScores": {},
    "measurements": {
      "chest": "85cm",
      "shoeSize": "40",
      "hips": "95cm",
      "waist": "73cm"
    },
    "journey": "Profil créé automatiquement après validation du casting.",
    "height": "1.70cm",
    "isPublic": false,
    "id": "ngoua-christy-3417",
    "experience": "Nouveau mannequin issu du casting. Score: 6.75/10",
    "location": "",
    "portfolioImages": [],
    "email": "",
    "level": "Pro"
  },
  {
    "email": "noemi.kim@example.com",
    "height": "1m78",
    "isPublic": true,
    "password": "noemi2024",
    "username": "Man-PMMN01",
    "gender": "Femme",
    "journey": "Découverte lors d'un casting sauvage, Noemi a rapidement gravi les échelons grâce à sa détermination. Formée au sein de la PMM Classroom, elle incarne aujourd'hui l'excellence et l'ambition de l'agence.",
    "categories": [
      "Défilé",
      "Éditorial",
      "Beauté"
    ],
    "quizScores": {
      "module-1-les-fondamentaux-du-mannequinat": {
        "total": 3,
        "timesLeft": 0,
        "score": 3,
        "timestamp": "2024-07-01T10:00:00Z"
      },
      "module-2-techniques-de-podium-catwalk": {
        "total": 2,
        "score": 2,
        "timestamp": "2024-07-02T10:00:00Z",
        "timesLeft": 0
      }
    },
    "id": "noemi-kim",
    "portfolioImages": [
      "https://i.ibb.co/z5TzL2M/casting-bg.jpg",
      "https://i.ibb.co/K2wS0Pz/hero-bg.jpg",
      "https://i.ibb.co/C5rcPJHz/titostyle-53.jpg"
    ],
    "distinctions": [
      {
        "titles": [
          "Miss Gabon 2022",
          "Top Model Afrique Centrale 2023"
        ],
        "name": "Palmarès National & International"
      }
    ],
    "name": "Noemi Kim",
    "age": 23,
    "location": "Libreville",
    "phone": "+241077000001",
    "imageUrl": "https://placehold.co/400x600/101010/D4AF37?text=Noemi+Kim",
    "measurements": {
      "waist": "62cm",
      "shoeSize": "40",
      "hips": "90cm",
      "chest": "85cm"
    },
    "experience": "Mannequin vedette de l'agence, Noemi a défilé pour les plus grands créateurs gabonais et a été le visage de plusieurs campagnes nationales. Son professionnalisme et sa démarche captivante en font une référence.",
    "level": "Pro"
  },
  {
    "level": "Pro",
    "distinctions": [],
    "measurements": {
      "waist": "65cm",
      "shoeSize": "39",
      "hips": "92cm",
      "chest": "82cm"
    },
    "phone": "065834453",
    "age": 21,
    "height": "1.67cm",
    "password": "carine2026",
    "username": "Man-PMMC01",
    "categories": [],
    "journey": "Profil créé automatiquement après validation du casting.",
    "id": "nsa-carine-7694",
    "isPublic": false,
    "name": "Carine NSA",
    "location": "",
    "imageUrl": "https://i.ibb.co/fVBxPNTP/T-shirt.png",
    "email": "",
    "experience": "Nouveau mannequin issu du casting. Score: 7.75/10",
    "gender": "Femme",
    "quizScores": {},
    "portfolioImages": []
  },
  {
    "location": "",
    "phone": "076216520",
    "experience": "Nouveau mannequin issu du casting. Score: 6.25/10",
    "password": "chancia2026",
    "categories": [],
    "height": "1.80cm",
    "name": "Chancia NTOSANG",
    "gender": "Femme",
    "journey": "Profil créé automatiquement après validation du casting.",
    "imageUrl": "https://i.ibb.co/fVBxPNTP/T-shirt.png",
    "distinctions": [],
    "quizScores": {},
    "measurements": {
      "shoeSize": "40",
      "waist": "68cm",
      "chest": "86cm",
      "hips": "97cm"
    },
    "age": 21,
    "portfolioImages": [],
    "isPublic": false,
    "username": "Man-PMMC06",
    "id": "ntosang-chancia-1960",
    "email": "",
    "level": "Pro"
  },
  {
    "journey": "Parcours à renseigner par l'administrateur.",
    "experience": "A une expérience préalable en agence et a participé à des défilés ou des campagnes locales.",
    "imageUrl": "https://i.ibb.co/fVBxPNTP/T-shirt.png",
    "gender": "Femme",
    "location": "Libreville ",
    "age": 24,
    "height": "164cm",
    "password": "raina2026",
    "username": "Man-PMMR01",
    "email": "ntsamecambelle26@gmail.com",
    "phone": "077092185",
    "name": "Raïna Ntsame",
    "quizScores": {},
    "isPublic": false,
    "id": "ntsame-rana-casting-1764963355022",
    "distinctions": [],
    "measurements": {
      "waist": "69cm",
      "hips": "90cm",
      "chest": "78cm",
      "shoeSize": "38"
    },
    "categories": [
      "Défilé",
      "Commercial"
    ],
    "level": "Pro",
    "portfolioImages": []
  },
  {
    "portfolioImages": [],
    "level": "Pro",
    "isPublic": false,
    "categories": [],
    "username": "Man-PMMD01",
    "journey": "Profil créé automatiquement après validation du casting.",
    "gender": "Femme",
    "location": "",
    "name": "Darcy OBIANG",
    "height": "1.77cm",
    "phone": "077563045",
    "password": "darcy2026",
    "id": "obiang-darcy-6152",
    "email": "",
    "measurements": {
      "hips": "91cm",
      "shoeSize": "40",
      "waist": "67cm",
      "chest": "83cm"
    },
    "imageUrl": "https://i.ibb.co/fVBxPNTP/T-shirt.png",
    "experience": "Nouveau mannequin issu du casting. Score: 6.75/10",
    "age": 18,
    "distinctions": [],
    "quizScores": {}
  },
  {
    "measurements": {
      "chest": "89cm",
      "waist": "72cm",
      "hips": "94cm",
      "shoeSize": "40"
    },
    "isPublic": false,
    "email": "",
    "gender": "Femme",
    "phone": "077207409",
    "age": 20,
    "quizScores": {},
    "location": "",
    "journey": "Profil créé automatiquement après validation du casting.",
    "name": "Chancelia OSSAGHA",
    "id": "ossagha-chancelia-5109",
    "imageUrl": "https://i.ibb.co/fVBxPNTP/T-shirt.png",
    "distinctions": [],
    "level": "Pro",
    "username": "Man-PMMC02",
    "password": "chancelia2026",
    "experience": "Nouveau mannequin issu du casting. Score: 6.75/10",
    "categories": [],
    "height": "1.69cm",
    "portfolioImages": []
  },
  {
    "categories": [],
    "height": "1.62cm",
    "username": "Man-PMMA03",
    "measurements": {
      "hips": "83cm",
      "shoeSize": "38",
      "chest": "73cm",
      "waist": "65cm"
    },
    "id": "padou-anne-4038",
    "isPublic": false,
    "portfolioImages": [],
    "age": 23,
    "phone": "066429254",
    "imageUrl": "https://i.ibb.co/fVBxPNTP/T-shirt.png",
    "level": "Pro",
    "password": "anne2026",
    "distinctions": [],
    "name": "Anne PADOU",
    "quizScores": {},
    "gender": "Femme",
    "email": "",
    "experience": "Nouveau mannequin issu du casting. Score: 6.63/10",
    "journey": "Profil créé automatiquement après validation du casting.",
    "location": ""
  },
  {
    "location": "",
    "imageUrl": "https://i.ibb.co/fVBxPNTP/T-shirt.png",
    "distinctions": [],
    "isPublic": false,
    "journey": "Profil créé automatiquement après validation du casting.",
    "measurements": {
      "hips": "99cm",
      "shoeSize": "41",
      "chest": "86cm",
      "waist": "70cm"
    },
    "age": 25,
    "gender": "Femme",
    "password": "dorcas2026",
    "id": "saphou-dorcas-8544",
    "level": "Pro",
    "username": "Man-PMMD02",
    "name": "Dorcas SAPHOU",
    "categories": [],
    "experience": "Nouveau mannequin issu du casting. Score: 6.25/10",
    "phone": "+212779732777",
    "quizScores": {},
    "height": "1.87cm",
    "portfolioImages": [],
    "email": ""
  },
  {
    "username": "Man-PMML01",
    "location": "",
    "gender": "Femme",
    "password": "laure2026",
    "journey": "Profil créé automatiquement après validation du casting.",
    "categories": [],
    "id": "seke-laure-9127",
    "quizScores": {},
    "experience": "Nouveau mannequin issu du casting. Score: 6.92/10",
    "portfolioImages": [],
    "isPublic": false,
    "age": 19,
    "name": "Laure SEKE",
    "measurements": {
      "waist": "68cm",
      "hips": "98cm",
      "shoeSize": "38",
      "chest": "80cm"
    },
    "distinctions": [],
    "email": "",
    "level": "Pro",
    "imageUrl": "https://i.ibb.co/fVBxPNTP/T-shirt.png",
    "phone": "066439461",
    "height": "1.77cm"
  },
  {
    "id": "sendze-lucresse-5454",
    "age": 21,
    "name": "Lucresse SENDZE",
    "phone": "077110862",
    "height": "1.60cm",
    "portfolioImages": [],
    "email": "",
    "quizScores": {},
    "categories": [],
    "location": "",
    "isPublic": false,
    "journey": "Profil créé automatiquement après validation du casting.",
    "gender": "Femme",
    "experience": "Nouveau mannequin issu du casting. Score: 5.75/10",
    "imageUrl": "https://i.ibb.co/fVBxPNTP/T-shirt.png",
    "measurements": {
      "hips": "84cm",
      "shoeSize": "37",
      "chest": "73cm",
      "waist": "62cm"
    },
    "password": "lucresse2026",
    "username": "Man-PMML03",
    "distinctions": [],
    "level": "Pro"
  },
  {
    "gender": "Femme",
    "distinctions": [],
    "portfolioImages": [],
    "username": "Man-PMMD03",
    "location": "",
    "level": "Pro",
    "isPublic": false,
    "name": "Diane TCHIBNDA",
    "phone": "074479062",
    "id": "tchibnda-diane-0842",
    "imageUrl": "https://i.ibb.co/fVBxPNTP/T-shirt.png",
    "journey": "Profil créé automatiquement après validation du casting.",
    "measurements": {
      "shoeSize": "41",
      "chest": "82cm",
      "waist": "73cm",
      "hips": "96cm"
    },
    "password": "diane2026",
    "age": 21,
    "experience": "Nouveau mannequin issu du casting. Score: 6.25/10",
    "height": "1.82cm",
    "email": "",
    "categories": [],
    "quizScores": {}
  },
  {
    "categories": [
      "Défilé",
      "Costume",
      "Sportswear"
    ],
    "imageUrl": "https://placehold.co/400x600/101010/D4AF37?text=Yann+Aubin",
    "experience": "Spécialiste du prêt-à-porter masculin, Yann est reconnu pour sa démarche puissante et son élégance naturelle. Il est un choix privilégié pour les défilés de créateurs de costumes.",
    "measurements": {
      "shoeSize": "44",
      "hips": "95cm",
      "chest": "98cm",
      "waist": "78cm"
    },
    "portfolioImages": [
      "https://i.ibb.co/TBt9FBSv/AJC-4630.jpg"
    ],
    "distinctions": [
      {
        "titles": [
          "Mannequin Homme de l'Année - PFD Awards 2025",
          "Prix de l'Élégance Masculine - Libreville Fashion Week"
        ],
        "name": "Podiums Masculins"
      }
    ],
    "id": "yann-aubin",
    "height": "1m88",
    "username": "Man-PMMY01",
    "quizScores": {
      "module-2-techniques-de-podium-catwalk": {
        "timesLeft": 0,
        "score": 2,
        "total": 2,
        "timestamp": "2024-07-05T10:00:00Z"
      }
    },
    "isPublic": true,
    "password": "yann2024",
    "gender": "Homme",
    "journey": "Ancien athlète, Yann a apporté sa discipline et sa prestance au monde du mannequinat. Il s'est rapidement imposé comme une figure incontournable de la mode masculine au Gabon.",
    "level": "Pro",
    "name": "Yann Aubin"
  }
];
